config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :tags
  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :body
  has_many :comments
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :author_name, :body
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings


  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :destroy, :edit, :update]

  def index
    @articles = Article.all
  end

  def show
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash.notice = "Article #{@article.title} Created Successfully"
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    flash.notice = "Article #{@article.title} Deleted Successfully"
    redirect_to articles_path
  end

  def edit

  end

  def update
    @article.update(article_params)
    flash.notice = "Article #{@article.title} Updated Successfully"
    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    # flash.notice = "Comment #{@comment} Created Successfully"
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # before_action :set_tag, only: [:create, :destroy, :edit, :update]
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  # def set_tag
  #   @tag = Tag.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_comment.html.erb
<h3>Comments (<%= @article.comments.size %>)</h3>
<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
<ul>
  <% @article.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</p>
<p
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>
</p>
<p>
  <% if @article.image.exists? %>
  <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br/>
  <%= f.file_field :image %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article_path(article), class: 'article-title' %>
  </li>
  <% end %>
</ul>


<%= link_to "Create a New Article", new_article_path, class: "new-article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= form_for(@article) do |f| %>
<ul>
  <% @article.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</p>
<p
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
  <p>
    Tags:
    <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>
  <p>
    <% if @article.image.exists? %>
    <%= image_tag @article.image.url(:medium) %>
    <% end %>
  </p>
  <p><%= @article.body %></p>
    <%= render partial: 'articles/comment', collection: @article.comments.reverse %>
    <%= render partial: 'comments/form' %>
    <%= link_to "<< Back to Articles list", articles_path %>
  <%= link_to "Delete", article_path(@article), method: :delete %>
  data: {confirm: "Really delete the article?"}
  <%= link_to "Edit", edit_article_path(@article) %>
</p>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f|  %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit "Submit" %><br/>
  </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul>
  <% @tags.each do |tag| %>
  <li>
    <%= link_to tag.name, tag_path(tag), class: "tag-title" %>
  </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
  <li>
    <%= link_to article.title, article_path(article) %>
  </li>
  <% end %>
</ul>
<%= link_to "Delete", tag_path(@tag), method: :delete %>